version: "3.3"

services:
  redis:
    image: redis:alpine

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  web:
    build: .
    ports:
      - 8080:8080
    environment:
      CONTAINER: true
      PORT: 8080
      REDIS_SERVICE: redis
      MONGO_SERVICE: mongodb://mongo:27017

volumes:
  mongodata: {}
