version: "3.7"
name: ls-m-r

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    command: mongod --quiet --logpath /dev/null

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DEBUG=2
      - HOSTNAME_EXTERNAL=127.0.0.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongodata: {}
